-- Signature visibility is saved per invoice; existing signatures remain visible.
begin;
alter table public.paperwork_invoices add column if not exists design_show_signature boolean not null default true;

create or replace function public._store_paperwork_invoices(p_scope uuid,p_data jsonb,p_position integer default 0,p_parent text default null) returns void language plpgsql set search_path=public as $$ declare item record; begin
insert into public.paperwork_invoices(firm_id,id,position,number,status,issue_date,service_date,due_date,billing_period,currency,vat_percent,client_id,note,logo,signature,paid_at,repeat_day,created_at,updated_at,issuer_name,issuer_address,issuer_city_country,issuer_tax_id_label,issuer_tax_id,issuer_reg_id_label,issuer_reg_no,issuer_email,client_name,client_address,client_city_country,client_tax_id_label,client_tax_id,client_reg_id_label,client_reg_no,client_email,bank_iban,bank_swift,bank_bank_name,design_template,design_accent_color,design_language,design_show_signature,design_seasonal_month,design_seasonal_variant) values (p_scope,p_data->>'id',p_position,coalesce(p_data #>> '{number}',''),coalesce(p_data #>> '{status}','draft'),nullif(p_data #>> '{issueDate}','')::date,nullif(p_data #>> '{serviceDate}','')::date,nullif(p_data #>> '{dueDate}','')::date,coalesce(p_data #>> '{billingPeriod}',''),coalesce(p_data #>> '{currency}','EUR'),coalesce(nullif(p_data #>> '{vatPercent}','')::numeric,0),p_data #>> '{clientId}',coalesce(p_data #>> '{note}',''),coalesce(p_data #>> '{logo}',''),coalesce(p_data #>> '{signature}',''),nullif(p_data #>> '{paidAt}','')::date,nullif(p_data #>> '{repeatDay}','')::integer,nullif(p_data #>> '{createdAt}','')::timestamptz,nullif(p_data #>> '{updatedAt}','')::timestamptz,coalesce(p_data #>> '{issuer,name}',''),coalesce(p_data #>> '{issuer,address}',''),coalesce(p_data #>> '{issuer,cityCountry}',''),coalesce(p_data #>> '{issuer,taxIdLabel}',''),coalesce(p_data #>> '{issuer,taxId}',''),coalesce(p_data #>> '{issuer,regIdLabel}',''),coalesce(p_data #>> '{issuer,regNo}',''),coalesce(p_data #>> '{issuer,email}',''),coalesce(p_data #>> '{client,name}',''),coalesce(p_data #>> '{client,address}',''),coalesce(p_data #>> '{client,cityCountry}',''),coalesce(p_data #>> '{client,taxIdLabel}',''),coalesce(p_data #>> '{client,taxId}',''),coalesce(p_data #>> '{client,regIdLabel}',''),coalesce(p_data #>> '{client,regNo}',''),coalesce(p_data #>> '{client,email}',''),coalesce(p_data #>> '{bank,iban}',''),coalesce(p_data #>> '{bank,swift}',''),coalesce(p_data #>> '{bank,bankName}',''),coalesce(p_data #>> '{design,template}','modern'),coalesce(p_data #>> '{design,accentColor}','#4f46e5'),coalesce(p_data #>> '{design,language}','en'),coalesce((p_data #>> '{design,showSignature}')::boolean,true),p_data #>> '{design,seasonalMonth}',nullif(p_data #>> '{design,seasonalVariant}','')::integer);
for item in select value,ordinality from jsonb_array_elements(coalesce(p_data #> '{items}','[]'::jsonb)) with ordinality loop
 perform public._store_paperwork_invoice_items(p_scope,item.value,item.ordinality::integer,p_data->>'id'); end loop;
end $$;

create or replace function public._read_paperwork_invoices(r public.paperwork_invoices) returns jsonb language sql stable security invoker set search_path=public as $$ select jsonb_build_object('id',r.id,'number',r.number,'status',r.status,'issueDate',r.issue_date,'serviceDate',r.service_date,'dueDate',r.due_date,'billingPeriod',r.billing_period,'currency',r.currency,'vatPercent',r.vat_percent,'clientId',r.client_id,'note',r.note,'logo',r.logo,'signature',r.signature,'paidAt',r.paid_at,'repeatDay',r.repeat_day,'createdAt',r.created_at,'updatedAt',r.updated_at,'issuer',jsonb_build_object('name',r.issuer_name,'address',r.issuer_address,'cityCountry',r.issuer_city_country,'taxIdLabel',r.issuer_tax_id_label,'taxId',r.issuer_tax_id,'regIdLabel',r.issuer_reg_id_label,'regNo',r.issuer_reg_no,'email',r.issuer_email),'client',jsonb_build_object('name',r.client_name,'address',r.client_address,'cityCountry',r.client_city_country,'taxIdLabel',r.client_tax_id_label,'taxId',r.client_tax_id,'regIdLabel',r.client_reg_id_label,'regNo',r.client_reg_no,'email',r.client_email),'bank',jsonb_build_object('iban',r.bank_iban,'swift',r.bank_swift,'bankName',r.bank_bank_name),'design',jsonb_build_object('template',r.design_template,'accentColor',r.design_accent_color,'language',r.design_language,'showSignature',r.design_show_signature,'seasonalMonth',r.design_seasonal_month,'seasonalVariant',r.design_seasonal_variant),'items',coalesce((select jsonb_agg(public._read_paperwork_invoice_items(c) order by c.position) from public.paperwork_invoice_items c where c.firm_id=r.firm_id and c.parent_id=r.id),'[]'::jsonb)) $$;

notify pgrst, 'reload schema';
commit;
